# Generated by Django 4.1 on 2022-08-15 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_choices_delete_choice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choices',
            new_name='Choice',
        ),
    ]
